services:
    Jupi\PrestaShopWebserviceBundle\Services\PrestaShopWebservice:
        arguments: ['', '', '']
        public: true

    jupi_prestashop_webservice:
        alias: Jupi\PrestaShopWebserviceBundle\Services\PrestaShopWebservice
        public: true

    Jupi\PrestaShopWebserviceBundle\Services\PrestaShopWebserviceExtra:
        arguments: ['', '', '']
        public: true

    jupi_prestashop_webservice_extra:
        alias: Jupi\PrestaShopWebserviceBundle\Services\PrestaShopWebserviceExtra
        public: true
